--nextval('tablename_colname_seq') per prossimo id

-- Inserimento di dati nella tabella 'utente'
INSERT INTO public.utente (nome, cognome, username, password, email, lingua, ruolo,numeroGiorni, mezzoTrasporto, punti, partitaIva, viaAlloggio, coordinateAlloggio)
VALUES ('Francesco', 'Di Lauro', 'Fry', 'despacito', 'francesco@email.com', 'EN', 'TURISTA', 5, 'Automobile', 80, NULL,'Via Bonaventura Poerio 6, Salerno', '406829364, 147660724'),
       ('Marco', 'Di Maio', 'Markio', 'password', 'marco@email.com', 'IT', 'TURISTA', 3, 'Piedi', 65, NULL, 'Corso Vittorio Emanuele', '40676866, 14766293'),
       ('Giovanni', 'Arcangeli', 'Giova', 'password', 'giovanni@email.com', 'EN', 'ESERCENTE', null, null, null, '12345678901', null, null),
       ('Fabiano', 'Campochiaro', 'Fabian', 'password', 'fabiano@email.com', 'IT', 'ESERCENTE', null, null, null, '12345678902', null, null);

-- Inserimento di dati nella tabella 'ristorante'
INSERT INTO public.ristorante (fk_esercente, nome, indirizzo, descrizione, punteggio,foto,coordinate) VALUES
         ('Giova', 'Il Pozzo Spagnolo', 'Via Fusandola 1/3', 'Consegna a domicilio, Da asporto, Prenotazioni online, Disponibilità di seggiolini da tavolo per bambini, Cucina italiana, Pesce, Cucina mediterranea, Cucina spagnola', 90, 'https://qul.imgix.net/9b49b845-3c3b-47c6-be65-ace7b9ba5aba/375939_sld.jpg', '4068016, 14753482'),
         ('Giova', 'Himiko', 'Via Roma 268', 'La nostra filosofia di vita é in diretta armonia con quella giapponese: ricerca della perfezione estetica e di gusti. Bellezza, rigore formale e sensibilitá estetica sono radicate nella tradizione.', 90, 'https://img.grouponcdn.com/deal/3g6b9SD9LxL85rg4VpDJQ4Vos7ed/3g-793x476/v1/c870x524.jpg', '406790015, 147544048'),
         ('Giova', 'Terraferma', 'Via Roma 270', 'rimanendo con i piedi fermi e stabili sulla terra, ma con la voglia di guardare lontano, verso l’infinito di quel mare che bagna le coste di una città che ha fatto della pesca parte integrante della sua storia.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/1d/83/b3/39/locale-moderno-con-una.jpg', '406790018, 147544026'),
         ('Giova', 'Anima e Cornicione', 'Via Portacatena 42', 'Anima & Cornicione è una pizzeria di Salerno, aperta nel 2020 da Agostino Pane. La pizza è quella classica napoletana mutuata dalle tante esperienze di Agostino nei locali italiani ed esteri.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/1b/9d/48/19/caption.jpg', '40679496, 14754712'),
         ('Giova', 'Gli Esposito', 'Via Roma 238', 'Salerno è un’isola felice per la ristorazione fuori casa senza glutine e a questa oasi sglutinata si aggiunge una chicca che sarà presto invidiata da chi vive lontano da questa città: la pizzeria Gli Esposito.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/14/ca/dc/f5/pignalosa-pizzeria-location.jpg', '406790942, 14755491'),
         ('Giova', 'Ristorante Mimmo e Lucio', 'Via Roma 264', 'Ristorante storico situato in una delle vie più centrali e frequentate di Salerno. Si distingue per la sua cucina semplice e casereccia.', 90, 'https://menu.sluurpy.it/foto-g/125629/3855713.jpg', '40679001, 147544092'),
         ('Giova', 'Galleon Pub Pizzeria', 'Via Roma 254', 'Il locale occupa una posizione centralissima nella città di Salerno, a pochi passi dal lungomare e vicino a luoghi istituzionali quali la sede del Comune, il palazzo della Provincia, la Prefettura e altri posti di interesse anche di carattere turistico.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/08/9b/c3/7a/galleon-pub.jpg', '40679035, 14754804'),
         ('Giova', 'Ingordo Sushi', 'Via Roma, 260', 'Un piccolo bistrot del gusto specializzato in sushi d''autore con ingredienti di primissima qualità e prodotti tipici giapponesi eccellenti.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/11/8c/f5/bd/migliore-ristorante-giapponese.jpg', '4067907, 14754429'),
         ('Giova', 'Ristorante Volte al Mare', 'Via Roma, 282-286', 'Alle porte del centro storico di  Salerno,  si aprono le volte del Ristorante.Una "trattoria e pizzeria", che vuole portare in tavola i piatti  della tradizione salernitana e campana rivisitati in chive moderna.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/28/65/e9/37/la-sala-interna.jpg', '406790884, 147542973'),
         ('Giova', 'Mini Pub 2.0', 'Piazza Matteo Luciani', 'Piatti tipici della cucina salernitana, personale gentile ed ospitale, servizio veloce', 90, 'https://media-cdn.tripadvisor.com/media/photo-l/2a/ca/c1/e0/caption.jpg', '406791665, 147527216'),
         ('Giova', 'Lola Wine Food & Tartare', 'Via Portacatena 1', 'Cucina italiana, Cucina peruviana, Pesce, Cucina sudamericana', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/1d/86/b4/bb/alici-imbottite-con-pickle.jpg', '40679547, 14755647'),
         ('Giova', 'Acqvamarina', 'Piazza Matteo Luciani 26', 'ACQVAMARINA è il ristorante di mare al Centro di Salerno, a pochissimi passi dal Teatro Verdi. Una cucina tradizionale di pesce con un pizzico di innovazione.', 90, 'https://img.restaurantguru.com/rf4e-Acqvamarina-Ristorante-di-Mare-design.jpg', '40679534, 1475261'),
         ('Giova', 'O''Cuzztiello', 'Via Roma 274', 'O'' Cuzzetiello arriva a Salerno... ma cos''è il Cuzzetiello? E'' la parte più sfiziosa del pane cafone, l''estremità dalla consistenza croccante e dalla forma tondeggiante farcito secondo la tradizione.', 90, 'https://media-cdn.tripadvisor.com/media/photo-p/19/e9/92/61/getlstd-property-photo.jpg', '406790024, 147543983'),
         ('Giova', 'Toc Toc', 'Via Porta di Mare 21', 'Toc Toc è sorpresa, gusto e divertimento alla portata di tutti. Primissima qualità per deliziare il vostro palato sotto forma di panini scostumati, di primi e secondi sempre diversi!', 90, 'https://res.cloudinary.com/tf-lab/image/upload/f_auto,q_auto,w_664,h_374/restaurant/f22d07ee-8ad8-4a06-9118-93ac0eb06a6b/c371d7cb-5f58-4818-9b6e-eee6f0168f6f.jpg', '40679251, 14756766'),
         ('Giova', 'Dodici Ventiquattro', 'Via Roma, 170', 'Ristorante molto accogliente, personale molto gentile e ottimo cibo.', 90, 'https://res.cloudinary.com/tf-lab/image/upload/f_auto,q_auto,w_664,h_374/restaurant/c0ce0ae3-c7e4-4d4f-8c00-30888a52b513/c514866c-e545-466b-8d38-fff4fc73cc88.jpg', '406788566, 147571194'),
         ('Giova', 'Baylon', 'Piazza Sedile del Campo, 6 Largo Campo', 'Sei alla ricerca del locale perfetto per le tue serate con gli amici? Il Pub Baylon il panino del Professore è il posto perfetto dove trascorrere del tempo in compagnia.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/13/26/17/b2/baylon.jpg', '40679862, 14755866'),
         ('Giova', 'Paninoteca Sant''Andrea', 'Piazza Sedile del Campo 13', 'Da sempre il Sant’Andrea segue la cucina tradizionale, dando però un tocco moderno ai nostri panini e piatti.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/0d/91/21/1b/sant-andrea-panineria.jpg', '40679673, 147560978'),
         ('Giova', 'Osteria Del Campo', 'Via Porta Catena 1 Largo Campo', 'Il ristorante propone oltre ad ottime pizze piatti tipici salernitani. È aperto tutti i giorni sia a pranzo che a cena tranne il martedì che è il giorno di chiusura.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/10/ef/ab/9d/osteria-del-campo.jpg', '41775489, 12921811'),
         ('Giova', 'Resilienza', 'Via Sabatini, 4', 'Resilienza nasce come Pizzeria di qualità nel 2013 a Salerno. La filosofia del km0, del biologico e del buono pulito e giusto riscuote subito successo.', 90, 'https://www.scattidigusto.it/wp-content/uploads/2021/01/pizzeria-Resilienza-Salerno-insegna-1280x1707.jpg', '40678355, 147500023'),
         ('Giova', 'Ristorante Sant''Andrea', 'Piazza Sedile del Campo, 13', 'Italiana, Pizza, Pesce, Mediterranea, Napoletana, Campana, Italiana (sud)', 90, 'https://salerno.esn.it/sites/esnsalerno.it/files/partners/images/ristorante_santandrea.png', '40679673, 147560978'),
         ('Giova', 'Bar Umberto Salerno', 'Via Roma 248', 'Il Bar Umberto è in via Roma, nel cuore del centro di Salerno.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/a4/98/c6/photo1jpg.jpg', '40679019, 14754972'),
         ('Giova', 'King''s Cross', 'Via Roma, 214', 'Situato nel cuore del centro storico di Salerno, il pub ristorante King''s Cross ti accoglie con deliziose specialità tipiche abbinate a una vasta selezione di birre di alta qualità.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/08/ec/09/0c/king-s-cross-irish-pub.jpg', '406788605, 147557408'),
         ('Giova', 'Ristorante Classico Salernitano', 'Via Portacatena, 1', 'Entrare nel Ristorante Tipico Salernitano significa fare un viaggio nella tradizione locale e mangiare la vera cucina di Salerno sia di mare che di terra.', 90, 'https://ristoranteclassicosalernitano.com/assets/img/web_2.jpg', '40679547, 14755647'),
         ('Giova', 'Da Nonno Raffaele', 'Vicolo Porta Rateprandi,19', 'Da Nonno Raffaele è un locale molto frequentato nella zona di Centro Storico. Che tu sia alla ricerca di un pasto leggero o di un''esperienza gastronomica completa, esplora i piatti del Da Nonno Raffaele e sperimenta l''autentica cucina Italiana di Salerno.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/18/69/90/24/banco.jpg', '406803035, 147559363'),
         ('Giova', 'Botteghelle65', 'Via delle botteghelle 65', 'Salumeria storica con cucina e servizio di piccola ristorazione. La bottega è stata fondata nel 1919 dalla famiglia Conte, successivamente grazie al Maestro degustatore Pino Adinolfi si è posizionata fin da subito con prodotti di eccellenza locali e regionali, con particolare attenzione ai prodotti Slow-Food, BIO e con piatti di tipica cucina Salernitana.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/09/94/81/69/botteghelle65.jpg', '40680625, 147588878'),
         ('Giova', 'Ingordo', 'Via Roma 184', 'Molto più di un semplice burger, Ingordo è un esperienza di gusto e divertimento! I nostri prodotti sono scelti e selezionati accuratamente, tanto da rendere il nostri burger un’esperienza esclusiva!', 90, 'https://media-cdn.tripadvisor.com/media/photo-p/0e/4d/60/67/ingordo-best-burger-salerno.jpg', '406790093, 14754356'),
         ('Giova', 'Paninoteca da Pippo', 'Piazza Sedile del Campo 1', 'Ottimo kebab con prezzi davvero bassi per essere nel pieno centro storico di Salerno. Pippo e lo staff sono molto accoglienti e cordiali.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/1a/7b/01/8b/paninis-y-kabak.jpg', '406795011, 147559563'),
         ('Giova', 'Ristorante del centro storico', 'Via Roma, 208', 'Ristorante del Centro Storico si trova a Salerno, in via Roma al numero 208, è una trattoria tipica che offre un ampio assortimento di piatti di cucina mediterranea appositamente rivisitati. Ci occupiamo principalmente della preparazione di piatti a base di pesce fresco, ma ci sono anche tante specialità realizzate con carni selezionate presso i migliori allevamenti.', 90, 'https://media-cdn.tripadvisor.com/media/photo-s/06/71/1d/a0/logo_rotated_90.jpg', '406790093, 14754356');

-- Inserimento di dati nella tabella 'tour'
INSERT INTO public.tour (id, stato, username, numeroGiorni, dataGenerazione)
VALUES (nextval('tour_id_seq'),'CORSO', 'Fry',3,'2023-12-22'),
       (nextval('tour_id_seq'),'ARCHIVIATO', 'Markio',7,'2023-12-8');

-- Inserimento di dati nella tabella 'tappa'
INSERT INTO public.tappa (id, descrizione, nome, coordinate,foto) VALUES
 (nextval('tappa_id_seq'), 'Salerno è una città ricca di storia e cultura, e il Castello Arechi è uno dei suoi monumenti più importanti. Il castello si trova sulla cima del Monte Bonadies, a circa 300 metri sul livello del mare, e offre una vista panoramica mozzafiato della città e del Golfo di Salerno.', 'Castello Arechi', '40685584, 14755099', '/images/castello-arechi.jpg'),
 (nextval('tappa_id_seq'), 'Salerno è una città ricca di storia e cultura, e la Via dei Mercanti è una delle sue strade più antiche e affascinanti. La strada si trova nel centro storico della città, ed è un importante centro commerciale e culturale.', 'Via dei Mercanti', '40679020, 14759893', '/images/via-dei-mercanti.jpg'),
 (nextval('tappa_id_seq'), 'La Cattedrale di Salerno è uno dei monumenti più importanti della città. La chiesa è un capolavoro dell''architettura arabo-normanna, e ospita importanti opere d''arte, tra cui il mosaico di San Matteo.', 'Duomo di Salerno', '40680351, 14759387', '/images/duomo.jpg'),
 (nextval('tappa_id_seq'), 'Il Giardino della Minerva è un giardino botanico situato nel centro storico di Salerno. Il giardino è uno dei più antichi giardini botanici d''Italia, e ospita una ricca collezione di piante medicinali.', 'Giardino della minerva', '40681018, 14753851', '/images/giardino-minerva.jpg'),
 (nextval('tappa_id_seq'), 'Il Complesso Monumentale di Santa Sofia è un complesso religioso e culturale situato nel centro storico di Salerno ed è costituito da una chiesa, un monastero e un museo', 'Complesso monumentale di Santa Sofia', '40680665, 14757648', '/images/santa-sofia.jpg'),
 (nextval('tappa_id_seq'), 'Il Museo Diocesano di Salerno è un museo d''arte sacra situato nel centro storico della città e ospita una collezione di opere d''arte che coprono un periodo di tempo che va dal Medioevo al XVIII secolo.', 'Museo Diocesano', '40680821, 14760240', '/images/museo-diocesano.jpg'),
 (nextval('tappa_id_seq'), 'Il Museo archeologico di Salerno è un museo situato nel centro storico della città e ospita una collezione di reperti archeologici che coprono un periodo di tempo che va dalla preistoria all''epoca romana.', 'Museo Archeologico', '40679152, 14762394', '/images/museo-archeologico.jpg'),
 (nextval('tappa_id_seq'), 'La Pinacoteca Provinciale di Salerno è un museo di arte situato nel centro storico della città. Il museo ospita una collezione di dipinti che coprono un periodo di tempo che va dal Medioevo al XIX secolo.', 'Pinacoteca provinciale', '40678968, 14760127', '/images/pinacoteca.jpg'),
 (nextval('tappa_id_seq'), 'Il Palazzo Pinto di Salerno è un palazzo storico situato nel centro storico della città. Il palazzo è uno dei più importanti esempi di architettura barocca della Campania.', 'Palazzo Pinto', '40679028, 14759889', '/images/palazzo-pinto.jpg'),
 (nextval('tappa_id_seq'), 'Il Complesso Monumentale di San Pietro a Corte è un complesso storico e religioso situato nel centro storico di Salerno. Il complesso è costituito da una chiesa, un monastero e un museo.', 'Complesso monumentale di San Pietro a corte', '40679696, 14757438', '/images/complesso-s-pietro.jpg'),
 (nextval('tappa_id_seq'), 'Il Teatro Verdi di Salerno è un teatro lirico situato nel centro storico della città. Il teatro stato inaugurato nel 1872, ed è uno dei più importanti teatri lirici della Campania.', 'Teatro Verdi', '40679222, 14752324', '/images/teatro-verdi.jpg'),
 (nextval('tappa_id_seq'), 'Il Lungomare Trieste di Salerno è un lungomare lungo circa 2 chilometri che si affaccia sul Golfo di Salerno. Il lungomare è un luogo ideale per passeggiare, fare jogging o semplicemente rilassarsi e ammirare la vista.', 'Lungomare Trieste', '40676934, 14761764', '/images/lungomare-trieste.jpg'),
 (nextval('tappa_id_seq'), 'Piazza della Libertà è una piazza situata nel centro storico di Salerno. La piazza è stata inaugurata nel 2021 e rappresenta la nuova visione della città verso un futuro sempre più orientato al turismo.', 'Piazza della Libertà', '40676541, 14753412', '/images/piazza-liberta.jpg'),
 (nextval('tappa_id_seq'), 'La stazione marittima di Salerno è una struttura moderna situata nel porto di Salerno. La stazione è stata inaugurata nel 2016 e rappresenta una nuova visione dell''architettura portuale.', 'Stazione marittima', '40674860, 14751789', '/images/stazione-marittima.jpg'),
 (nextval('tappa_id_seq'), 'Il Corso Vittorio Emanuele è la principale via dello shopping di Salerno. Il corso è un luogo vivace e animato, che ospita negozi, ristoranti e bar.', 'Corso Vittorio Emanuele', '40676865, 14766292', '/images/corso-v-emanuele.png'),

INSERT INTO public.tappaTour (idTour, idTappa, isCompletata)
VALUES (1,1,true),
       (1,2,false);
        (1,3,false);
        (1,4,false);
        (1,5,false);
        (1,6,true);
        (1,7,false);
        (1,8,false);
        (1,9,false);
        (1,10,false);

-- Inserimento di dati nella tabella 'sezione'
INSERT INTO public.sezione (id, descrizione,foto, idTappa, titolo, numero)
VALUES (nextval('sezione_id_seq'),'Salerno è una città ricca di storia e cultura, e il Castello Arechi è uno dei suoi monumenti più importanti. Il castello si trova sulla cima del Monte Bonadies, a circa 300 metri sul livello del mare, e offre una vista panoramica mozzafiato della città e del Golfo di Salerno.','/images/sezioni/Castello/Introduzione.png', 1,'Introduzione',1),
       (nextval('sezione_id_seq'),'È bene partire dalla Porta d’ingresso, che risale al XIII secolo. La porta conduce al Cortile delle Armi, dove si trova la Torre del Cavaliere, che ospita un museo archeologico con reperti provenienti dal territorio salernitano.','/images/sezioni/Castello/ingresso.png', 1,'Ingresso',2),
       (nextval('sezione_id_seq'),'Dal Cortile delle Armi, si prosegue per il Cortile del Belvedere, che offre una vista spettacolare sul Golfo di Salerno. Il cortile è circondato da un portico, sotto il quale si trovano le sale del castello, tra cui la Sala del Trono, la Sala delle Armi e la Sala delle Feste.','/images/sezioni/Castello/belvedere.png', 1,'Belvedere',3),
       (nextval('sezione_id_seq'),'Al termine della visita al castello, è possibile salire sulla Torre dell’Orologio, che offre una vista ancora più panoramica della città e del golfo.','/images/sezioni/Castello/orologio.png', 1,'Torre dell’orologio',4),
       (nextval('sezione_id_seq'),'Il Castello Arechi fu costruito nel IX secolo dai Longobardi, che governavano la Campania in quel periodo e fu poi ampliato e fortificato dai Normanni, che conquistarono la Campania nel XI secolo. Nel corso dei secoli, il castello ha svolto un ruolo importante nella storia di Salerno.','/images/sezioni/Castello/storia.png', 1,'La storia del castello',5),
       (nextval('sezione_id_seq'),'Salerno è una città ricca di storia e cultura, e la Via dei Mercanti è una delle sue strade più antiche e affascinanti. La strada si trova nel centro storico della città, ed è un importante centro commerciale e culturale.','/images/sezioni/Mercanti/Introduzione.png', 2,'Introduzione',1),
       (nextval('sezione_id_seq'),'La Via dei Mercanti esiste fin dall’epoca romana, quando era una strada importante per il commercio. La strada fu poi ampliata e rinnovata durante il Medioevo, quando Salerno era un importante centro commerciale e culturale.','/images/sezioni/Mercanti/storia.png', 2,'La storia dei Mercanti',2),
       (nextval('sezione_id_seq'),'La visita parte dalla Porta di San Francesco, che si trova all’inizio della strada. La porta risale al XIII secolo, ed è uno dei monumenti più importanti della città.','/images/sezioni/Mercanti/porta.png', 2,'Porta di San Francesco',3),
       (nextval('sezione_id_seq'),'Dalla Porta di San Francesco, la visita prosegue lungo la strada, che è ricca di negozi e botteghe. Si possono trovare negozi di abbigliamento, di souvenir, di prodotti tipici locali e molto altro ancora.','/images/sezioni/Mercanti/negozi.png', 2,'Negozi',4),
       (nextval('sezione_id_seq'),'La Cattedrale di Salerno è uno dei monumenti più importanti della città. La chiesa è un capolavoro dell’architettura arabo-normanna, e ospita importanti opere d’arte, tra cui il mosaico di San Matteo.','/images/sezioni/Duomo/Introduzione.png', 3,'Introduzione',1),
       (nextval('sezione_id_seq'),'La Cattedrale di Salerno fu costruita nel XI secolo, durante il regno di Guaimaro IV. La chiesa fu dedicata a San Matteo, il patrono della città. La cattedrale fu ampliata e rinnovata nel XII secolo, durante il regno di Guglielmo I.','/images/sezioni/Duomo/storia.png', 3,'La storia della cattedrale',2),
       (nextval('sezione_id_seq'),'La facciata è in stile romanico, e presenta un portale riccamente decorato.','/images/sezioni/Duomo/facciata.png', 3,'La facciata',3),
       (nextval('sezione_id_seq'),'Dalla facciata, la visita prosegue all’interno della chiesa. L’interno della chiesa è a tre navate, e presenta un’atmosfera solenne e suggestiva.','/images/sezioni/Duomo/chiesa.png', 3,'La chiesa',4),
       (nextval('sezione_id_seq'),'Tra le opere d’arte più importanti della Cattedrale di Salerno ci sono: •Il mosaico di San Matteo, che si trova nel presbiterio. Il mosaico, risalente al XII secolo, è un capolavoro dell’arte bizantina. •	La cripta, che ospita le spoglie di San Matteo.','/images/sezioni/Duomo/opere.png', 3,'Le opere d’arte',5),
       (nextval('sezione_id_seq'),'Il Giardino della Minerva è un giardino botanico situato nel centro storico di Salerno. Il giardino è uno dei più antichi giardini botanici d’Italia, e ospita una ricca collezione di piante medicinali.','/images/sezioni/GiardinoDellaMinerva/Introduzione.png', 4,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il Giardino della Minerva fu fondato nel X secolo da Costantino l’Africano, un medico e botanico di origine araba e fu inizialmente utilizzato per la coltivazione di piante medicinali, diventando un importante centro di studio e ricerca.','/images/sezioni/GiardinoDellaMinerva/storia.png', 4,'La storia del giardino',2),
       (nextval('sezione_id_seq'),'La visita inizia dalla Porta della Minerva, che si trova all’ingresso del giardino. La porta risale al XII secolo, ed è uno dei monumenti più importanti della città. Dalla Porta della Minerva, la visita prosegue attraverso il giardino, che è diviso in tre aree. ','/images/sezioni/GiardinoDellaMinerva/visita.png', 4,'La visita',3),
       (nextval('sezione_id_seq'),'Il Complesso Monumentale di Santa Sofia è un complesso religioso e culturale situato nel centro storico di Salerno ed è costituito da una chiesa, un monastero e un museo.','/images/sezioni/SantaSofia/introduzione.png', 5,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il complesso fu fondato alla fine del X secolo da un gruppo di monaci benedettini. La chiesa fu dedicata a Santa Sofia, la Sapienza divina. Il complesso fu ampliato e rinnovato nel XII secolo, durante il regno di Guglielmo I, in questo periodo, fu dotato di un monastero e di un museo. ','/images/sezioni/SantaSofia/storia.png', 5,'La storia del complesso',2),
       (nextval('sezione_id_seq'),'La chiesa è un esempio di architettura romanica. L’interno della chiesa è a tre navate, e presenta un’atmosfera solenne e suggestiva.','/images/sezioni/SantaSofia/chiesa.png', 5,'La chiesa',3),
       (nextval('sezione_id_seq'),'Il monastero è un esempio di architettura gotica. Il monastero ospita un chiostro, una biblioteca e un museo. Il museo ospita una collezione di opere d’arte, tra cui dipinti, sculture e oggetti liturgici','/images/sezioni/SantaSofia/monastero.png', 5,'Il monastero',4),
       (nextval('sezione_id_seq'),'Il Museo Diocesano di Salerno è un museo d’arte sacra situato nel centro storico della città e ospita una collezione di opere d’arte che coprono un periodo di tempo che va dal Medioevo al XVIII secolo.','/images/sezioni/MuseoDiocesano/introduzione.png', 6,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il Museo Diocesano di Salerno fu fondato nel 1980, e si trova nell’ex sede della scuola medica salernitana. Il museo ospita una collezione di opere d’arte che provengono da diverse chiese e conventi della diocesi di Salerno.','/images/sezioni/MuseoDiocesano/storia.png', 6,'La storia del museo',2),
       (nextval('sezione_id_seq'),'La collezione del Museo Diocesano di Salerno è composta da dipinti, sculture, oggetti liturgici e documenti storici. Tra le opere d’arte più importanti del museo ci sono: •	Il trittico di Simone Martini, un dipinto del XIV secolo che rappresenta la Madonna con il Bambino e i santi.','/images/sezioni/MuseoDiocesano/collezione.png', 6,'La collezione',3),
       (nextval('sezione_id_seq'),'La sala dei dipinti ospita una collezione di dipinti che coprono un periodo di tempo che va dal XIV al XVIII secolo. Tra i dipinti esposti si possono trovare opere di Simone Martini, Giovanni Bellini, Luca Giordano e altri importanti artisti italiani.','/images/sezioni/MuseoDiocesano/SalaDipinti.png', 6,'La sala dei dipinti',4),
       (nextval('sezione_id_seq'),'Dalla sala dei dipinti, la visita prosegue nelle altre sale del museo, che ospitano una collezione di sculture, oggetti liturgici e documenti storici.','/images/sezioni/MuseoDiocesano/AltreSale.png', 6,'Altre sale',5),
       (nextval('sezione_id_seq'),'Il Museo archeologico di Salerno è un museo situato nel centro storico della città e ospita una collezione di reperti archeologici che coprono un periodo di tempo che va dalla preistoria all’epoca romana.','/images/sezioni/MuseoArcheologico/introduzione.png', 7,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il Museo archeologico di Salerno fu fondato nel 1870, e si trova nell’ex sede del convento di San Domenico. Il museo ospita una collezione di reperti archeologici che provengono da diverse località della provincia di Salerno','/images/sezioni/MuseoArcheologico/storia.png', 7,'La storia del museo',2),
       (nextval('sezione_id_seq'),'La collezione del Museo archeologico di Salerno è composta da reperti che testimoniano la storia della regione dalla preistoria all’epoca romana. Tra i reperti più importanti del museo ci sono: •	La Venere di Fratte, una statua in marmo risalente al I secolo a.C. che rappresenta una figura femminile nuda.','/images/sezioni/MuseoArcheologico/collezione.png', 7,'Collezione',3),
       (nextval('sezione_id_seq'),'La sala della Preistoria ospita una collezione di reperti che testimoniano la vita delle popolazioni che abitavano la regione prima dell’arrivo dei romani. Tra i reperti esposti si possono trovare utensili in pietra, ceramiche e ossa di animali.','/images/sezioni/MuseoArcheologico/SalaPreistoria.png', 7,'La sala della preistoria',4),
       (nextval('sezione_id_seq'),'Dalla sala della Preistoria, la visita prosegue nelle altre sale del museo, che ospitano una collezione di reperti dell’età greca, romana e medievale.','/images/sezioni/MuseoArcheologico/altreSale.png', 7,'Altre sale',5),
       (nextval('sezione_id_seq'),'La Pinacoteca Provinciale di Salerno è un museo di arte situato nel centro storico della città. Il museo ospita una collezione di dipinti che coprono un periodo di tempo che va dal Medioevo al XIX secolo.','/images/sezioni/PinacotecaProvinciale/introduzione.png', 8,'Introduzione',1),
       (nextval('sezione_id_seq'),'La Pinacoteca Provinciale di Salerno fu fondata nel 1866, e si trova nell’ex sede del convento di San Giorgio. Il museo ospita una collezione di dipinti che provengono da diverse chiese e conventi della provincia di Salerno.','/images/sezioni/PinacotecaProvinciale/storia.png', 8,'La storia della pinacoteca',2),
       (nextval('sezione_id_seq'),'La collezione della Pinacoteca Provinciale di Salerno è composta da dipinti di artisti italiani e stranieri. Tra le opere d’arte più importanti del museo ci sono: •	La Madonna della Neve, un dipinto del XIV secolo attribuito a Simone Martini. •	La Pala di San Giorgio, un dipinto del XV secolo di Andrea Sabatini. ','/images/sezioni/PinacotecaProvinciale/collezione.png', 8,'La collezione',3),
       (nextval('sezione_id_seq'),'La sala dei dipinti del XIV secolo ospita una collezione di dipinti che rappresentano la scuola pittorica napoletana del XIV secolo. Tra i dipinti esposti si possono trovare opere di Simone Martini, Andrea Sabatini e altri importanti artisti italiani.','/images/sezioni/PinacotecaProvinciale/salaDipinti.png', 8,'La sala del XIV secolo',4),
       (nextval('sezione_id_seq'),'Dalla sala dei dipinti del XIV secolo, la visita prosegue nelle altre sale del museo, che ospitano una collezione di dipinti del XV, XVI, XVII e XVIII secolo.','/images/sezioni/PinacotecaProvinciale/altreSale.png', 8,'Altre sale',5),
       (nextval('sezione_id_seq'),'Il Palazzo Pinto di Salerno è un palazzo storico situato nel centro storico della città. Il palazzo è uno dei più importanti esempi di architettura barocca della Campania.','/images/sezioni/PalazzoPinto/introduzione.png', 9,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il Palazzo Pinto fu costruito nel XVII secolo per volere della famiglia Pinto, una delle più importanti famiglie nobiliari di Salerno. Il palazzo fu progettato dall’architetto Francesco Antonio Picchiatti, ed è considerato uno dei suoi capolavori.','/images/sezioni/PalazzoPinto/storia.png', 9,'La storia',2),
       (nextval('sezione_id_seq'),'La facciata del Palazzo Pinto è un capolavoro dell’architettura barocca ed è riccamente decorata con stucchi, colonne e statue. Il portale del Palazzo Pinto è uno dei più importanti esempi di architettura barocca di Salerno ed è sormontato da un timpano curvilineo, con un ricco ornamento scultoreo','/images/sezioni/PalazzoPinto/facciata.png', 9,'La facciata',3),
       (nextval('sezione_id_seq'),'Il cortile del Palazzo Pinto è un’altra opera d’arte dell’architettura barocca ed è circondato da colonne e arcate','/images/sezioni/PalazzoPinto/cortile.png', 9,'Il cortile',4),
       (nextval('sezione_id_seq'),'Gli interni del Palazzo Pinto sono sontuosi e raffinati, decorati con stucchi, affreschi e mobili d’epoca.','/images/sezioni/PalazzoPinto/interni.png', 9,'Gli interni',5),
       (nextval('sezione_id_seq'),'Il salone delle feste è la sala più importante del Palazzo Pinto. Il salone è decorato con affreschi del XVIII secolo, che rappresentano scene mitologiche.','/images/sezioni/PalazzoPinto/saloneFeste.png', 9,'Il salone delle feste',6),
       (nextval('sezione_id_seq'),'Il Complesso Monumentale di San Pietro a Corte è un complesso storico e religioso situato nel centro storico di Salerno. Il complesso è costituito da una chiesa, un monastero e un museo.','/images/sezioni/ComplessoMonumentaleSPietro/introduzione.png', 10,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il complesso fu fondato alla fine del X secolo da un gruppo di monaci benedettini. La chiesa fu dedicata a San Pietro a Corte, in riferimento alla sua posizione all’interno del palazzo del principe longobardo Arechi II. ','/images/sezioni/ComplessoMonumentaleSPietro/storia.png', 10,'La storia',2),
       (nextval('sezione_id_seq'),'La chiesa è un esempio di architettura romanica. L’interno è a tre navate e presenta un’atmosfera solenne e suggestiva.','/images/sezioni/ComplessoMonumentaleSPietro/chiesa.png', 10,'La chiesa',3),
       (nextval('sezione_id_seq'),'Il monastero è un esempio di architettura gotica e ospita un chiostro, una biblioteca e un museo. Il museo ospita una collezione di opere d’arte, tra cui dipinti, sculture e oggetti liturgici.','/images/sezioni/ComplessoMonumentaleSPietro/monastero.png', 10,'Il monastero',4),
       (nextval('sezione_id_seq'),'Il Teatro Verdi di Salerno è un teatro lirico situato nel centro storico della città. Il teatro stato inaugurato nel 1872, ed è uno dei più importanti teatri lirici della Campania.','/images/sezioni/TeatroVerdi/introduzione.png', 11,'Introduzione',1),
       (nextval('sezione_id_seq'),'La costruzione del teatro fu deliberata dal Consiglio Comunale di Salerno nel 1863, su proposta dell’allora Sindaco Matteo Valiante. I lavori di costruzione furono affidati all’architetto Antonio D’Amora e all’ingegnere Giuseppe Menichini. ','/images/sezioni/TeatroVerdi/storia.png', 11,'La storia',2),
       (nextval('sezione_id_seq'),'Il Teatro Verdi è un teatro a struttura lignea, con quattro ordini di palchi e un loggione. La facciata del teatro è in stile neoclassico, e presenta un portico con colonne corinzie. L’interno del teatro è abbellito da stucchi, affreschi e decorazioni in stile neoclassico. ','/images/sezioni/TeatroVerdi/architettura.png', 11,'Architettura',3),
       (nextval('sezione_id_seq'),'Il Teatro Verdi ospita una stagione teatrale che si svolge da ottobre a maggio. La stagione comprende opere liriche, balletti e concerti.','/images/sezioni/TeatroVerdi/stagioneTeatrale.png', 11,'La stagione teatrale',4),
       (nextval('sezione_id_seq'),'Il Lungomare Trieste di Salerno è un lungomare lungo circa 2 chilometri che si affaccia sul Golfo di Salerno. Il lungomare è un luogo ideale per passeggiare, fare jogging o semplicemente rilassarsi e ammirare la vista','/images/sezioni/Lungomare/Introduzione.png', 12,'Introduzione',1),
       (nextval('sezione_id_seq'),'La costruzione del lungomare fu avviata nel 1870 e fu completata nei primi anni del XX secolo. Il lungomare fu progettato dall’ingegnere Francesco Antonio Picchiatti, ed è considerato uno dei più importanti esempi di architettura liberty della Campania.','/images/sezioni/Lungomare/storia.png', 12,'La storia',2),
       (nextval('sezione_id_seq'),'Il Lungomare Trieste è oggi un’importante attrattiva turistica di Salerno ed è frequentato da turisti e cittadini di tutte le età, che lo scelgono per trascorrere il tempo libero o per fare una passeggiata romantica','/images/sezioni/Lungomare/lungomareOggi.png', 12,'Il lungomare oggi',3),
       (nextval('sezione_id_seq'),'Piazza della Libertà è una piazza situata nel centro storico di Salerno. La piazza è stata inaugurata nel 2021 e rappresenta la nuova visione della città verso un futuro sempre più orientato al turismo.','/images/sezioni/PiazzaDellaLibertà/introduzione.png', 13,'Introduzione',1),
       (nextval('sezione_id_seq'),'Piazza della Libertà è stata costruita sul sito dell’ex porto commerciale di Salerno. I lavori di costruzione sono stati avviati nel 2018 e sono stati completati nel 2021. La piazza è stata progettata dall’architetto catalano Ricardo Bofill.','/images/sezioni/PiazzaDellaLibertà/storia.png', 13,'La storia della piazza',2),
       (nextval('sezione_id_seq'),'Piazza della Libertà è una piazza semicircolare, leggermente rialzata rispetto al livello circostante. La piazza è circondata da un Crescent, un edificio a forma di mezzaluna che ospita negozi, ristoranti e uffici.','/images/sezioni/PiazzaDellaLibertà/architettura.png', 13,'L’architettura della piazza',3),
       (nextval('sezione_id_seq'),'Piazza della Libertà è oggi una delle principali attrazioni turistiche di Salerno ed è frequentata da turisti e cittadini di tutte le età, che la scelgono per passeggiare, fare shopping o semplicemente rilassarsi e ammirare la vista.','/images/sezioni/PiazzaDellaLibertà/LaPiazzaOggi.png', 13,'La piazza oggi',4),
       (nextval('sezione_id_seq'),'La stazione marittima di Salerno è una struttura moderna situata nel porto di Salerno. La stazione è stata inaugurata nel 2016 e rappresenta una nuova visione dell’architettura portuale.','/images/sezioni/StazioneMarittima/Introduzione.png', 14,'Introduzione',1),
       (nextval('sezione_id_seq'),'La costruzione della stazione marittima è stata avviata nel 2012 e è stata completata nel 2016. La stazione è stata progettata dall’architetto Zaha Hadid, ed è considerata uno dei suoi capolavori.','/images/sezioni/StazioneMarittima/storia.png', 14,'La storia della stazione',2),
       (nextval('sezione_id_seq'),'La stazione marittima è una struttura in vetro e acciaio, con una forma sinuosa e ondulata ed è circondata da una grande piazza, che ospita un’area verde e un’area per eventi.','/images/sezioni/StazioneMarittima/architettura.png', 14,'Architettura',3),
       (nextval('sezione_id_seq'),'La stazione marittima è oggi una delle principali attrazioni turistiche di Salerno ed è frequentata da turisti e cittadini di tutte le età, che la scelgono per passeggiare, fare shopping o semplicemente rilassarsi e ammirare la vista.','/images/sezioni/StazioneMarittima/oggi.png', 14,'La stazione oggi',4),
       (nextval('sezione_id_seq'),'Il Corso Vittorio Emanuele è la principale via dello shopping di Salerno. Il corso è un luogo vivace e animato, che ospita negozi, ristoranti e bar.','/images/sezioni/CorsoVittEman/introduzione.png', 15,'Introduzione',1),
       (nextval('sezione_id_seq'),'Il Corso Vittorio Emanuele è stato costruito nel XIX secolo, durante il Risorgimento italiano. Il corso fu intitolato a Vittorio Emanuele II, il primo re d’Italia.','/images/sezioni/CorsoVittEman/storia.png', 15,'La storia',2),
       (nextval('sezione_id_seq'),'Il Corso Vittorio Emanuele è un corso alberato, con un’ampia passeggiata pedonale ed è fiancheggiato da edifici storici, che risalgono al XIX e al XX secolo.','/images/sezioni/CorsoVittEman/architettura.png', 15,'Architettura del corso',3),
       (nextval('sezione_id_seq'),'Il Corso Vittorio Emanuele è oggi una delle principali attrazioni turistiche di Salerno. Il corso è frequentato da turisti e cittadini di tutte le età, che lo scelgono per fare shopping, mangiare o semplicemente passeggiare.','/images/sezioni/CorsoVittEman/oggi.png', 15,'Il corso oggi',4);
